### ISSUE TITLE
kill all non-hero non-dummy units inbetween every duel and every round

### ISSUE THREAD

**Issue by BLOKKADE** [BLOKKADE/CHS#10]

**Comment by ABlackDeath** [comment]
Aren't we already doing this? If not, don't kill the pet unit or the hero preview unit. Preview unit is removed after voting is all done.

**Comment by BLOKKADE** [comment]
I thought we did but there have been reports of players being able to kill others by getting summons to glitch outside of the arenas, so unless you've recently changed something about it we're not.
